package main

//goland:noinspection ALL
const (
	TCA_CAKE_UNSPEC = iota
	TCA_CAKE_PAD
	TCA_CAKE_BASE_RATE64
	TCA_CAKE_DIFFSERV_MODE
	TCA_CAKE_ATM
	TCA_CAKE_FLOW_MODE
	TCA_CAKE_OVERHEAD
	TCA_CAKE_RTT
	TCA_CAKE_TARGET
	TCA_CAKE_AUTORATE
	TCA_CAKE_MEMORY
	TCA_CAKE_NAT
	TCA_CAKE_RAW // was _ETHERNET
	TCA_CAKE_WASH
	TCA_CAKE_MPU
	TCA_CAKE_INGRESS
	TCA_CAKE_ACK_FILTER
	TCA_CAKE_SPLIT_GSO
	TCA_CAKE_FWMARK
)
