on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          v=${GITHUB_REF#refs/*/} ./release.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
